libs/juno-ui-components/src/components/RadioGroup/RadioGroup.component.js
libs/juno-ui-components/src/components/RadioGroup/RadioGroup.test.js
libs/juno-ui-components/src/components/RadioGroup/index.js

Adds a RadioGroup component that does not render any markup itself. The RadioGroup component makes sure all child radio elements have the same name attribute, thus requiring the name attribute to be passed only once as a prop to the group and not the individual children:
```
<RadioGroup name="my-radiogroup">
<Radio />
<Radio />
</RadioGroup>
```
instead of
```
<Radio name="my-radiogroup" />
<Radio name="my-radiogroup" />
```
will render:
```
<input type="radio" name="my-radiogroup" />
<input type="radio" name="my-radiogroup" />
```
RadioGroup adds convenience and can be used to render any labels and additional markup that might be required in the future. Individual naming will still work.

Radio group

---

libs/juno-ui-components/src/components/CheckboxGroup/CheckboxGroup.stories.js
libs/juno-ui-components/src/components/Form/Form.stories.js
libs/juno-ui-components/src/components/FormSection/FormSection.stories.js
libs/juno-ui-components/src/components/RadioGroup/RadioGroup.stories.js
libs/juno-ui-components/src/components/SelectRow/SelectRow.stories.js

rework nested stories so the actual Component name of child components shows up in storybook code samples (instead of 'bound component').

Improve storybook

---

libs/juno-ui-components/src/components/Message/Message.component.js

Icon is now positioned vertically in the message, no matter what the height of the message is.

[ui] Message: fix icon position, remove obsolete markup

---

libs/juno-ui-components/src/components/Button/Button.stories.js
libs/juno-ui-components/src/components/Icon/Icon.component.js
libs/juno-ui-components/src/components/Icon/Icon.stories.js
libs/juno-ui-components/src/components/Icon/Icon.test.js

* Icon component now accepts `href` prop (will render `<a>`)
* Icon button now accepts `onClick` handler as prop (will render `<button>`)
* In case both are passed `href` will trump `onClick` (can be changed later if sensible)
* ClickableIcon component still exists because legacy usage in apps

Icon clickable

---

libs/oauth/src/useOidcAuth.js

before was `options.silent !== false` and this leads to silent to be true if the option is not being set. It should be silent when the user sets the option silent to TRUE, everything else (also `undefined`) should be false.

[oauth] silent default false

---

libs/juno-ui-components/src/components/IntroBox/IntroBox.component.js
libs/juno-ui-components/src/components/IntroBox/IntroBox.test.js

avoid `<div> cannot appear as a descendant of <p>.`

[ui] render children as children and text in a p element

---

libs/juno-ui-components/src/components/Message/Message.component.js
libs/juno-ui-components/src/components/Message/Message.test.js

Allow get notified when a message is manually or automatically dismissed. This helps when cleaning up states where the messaged are mantained.

[ui] added callback on dismiss

---

libs/juno-ui-components/src/components/CheckboxRow/CheckboxRow.stories.js
libs/juno-ui-components/src/components/CheckboxRow/CheckboxRow.test.js
libs/juno-ui-components/src/components/RadioRow/RadioRow.stories.js
libs/juno-ui-components/src/components/RadioRow/RadioRow.test.js
libs/juno-ui-components/src/components/SelectRow/SelectRow.stories.js
libs/juno-ui-components/src/components/SelectRow/SelectRow.test.js
libs/juno-ui-components/src/components/SwitchRow/SwitchRow.stories.js
libs/juno-ui-components/src/components/SwitchRow/SwitchRow.test.js
libs/juno-ui-components/src/components/TextInputRow/TextInputRow.stories.js
libs/juno-ui-components/src/components/TextInputRow/TextInputRow.test.js
libs/juno-ui-components/src/components/TextareaRow/TextareaRow.stories.js
libs/juno-ui-components/src/components/TextareaRow/TextareaRow.test.js

* allows users to pass links (or any other ReactNodes) as helptext

[ui] Form Rows: add tests and stories for helptext containing nodes

---

libs/juno-ui-components/src/components/CodeBlock/CodeBlock.component.js
libs/juno-ui-components/src/components/CodeBlock/CodeBlock.stories.js
libs/juno-ui-components/src/components/CodeBlock/CodeBlock.test.js

* adds Tabbed Codeblock
* adds new props `tabs`, `contents` 
* does not render Tabs if no `tabs` and no `heading` was passed

Codeblock tabs

---

libs/juno-ui-components/src/components/FilterInput/FilterInput.component.js
libs/juno-ui-components/src/components/FilterInput/FilterInput.stories.js
libs/juno-ui-components/src/components/FilterInput/FilterInput.test.js
libs/juno-ui-components/src/components/Filters/Filters.component.js
libs/juno-ui-components/src/components/Filters/Filters.stories.js
libs/juno-ui-components/src/components/Filters/Filters.test.js

* FilterInput now accepts a `valuePlaceholder` prop as a string that will render as a placeholder in the filter value text input (as long as the component is not loading)
* fixed some stories: the correct name `keyLabel` of the prop to render as the default option in the filter key select element is now represented in all stories

Fix filters

---

libs/juno-ui-components/src/components/FilterInput/FilterInput.component.js
libs/juno-ui-components/src/components/FilterInput/FilterInput.test.js

This handler is being used when hitting enter key or when clicking on the filter icon. The event is different and from the outside hard to evaluate. If the event comes from the icon I don't have any chance to get the input value.
Since this event it is not tied to a html node we should instead return the value which is being used to filter.

[ui] FilterInput onFilter handler returns input value

---

libs/juno-ui-components/package.json
libs/juno-ui-components/src/components/Breadcrumb/Breadcrumb.component.js

use `React.Fragment` with key instead of unkeyed `<>`

[ui] Breadcrumb: fix key error

---

libs/juno-ui-components/src/components/Button/Button.component.js

Make sure Subdued buttons have widths compensating for their border width, resulting in identical width of Subdued and all other variants.

[ui] Button: fix Button widths

---

libs/juno-ui-components/package.json
libs/juno-ui-components/src/components/SelectDivider/SelectDivider.component.js
libs/juno-ui-components/src/components/SelectOptionGroup/SelectOptionGroup.component.js

In `SelectOptionGroup` and `SelectDivider`, the forwardedRef was not passed down as a ref inside the component, thus (presumably) causing React warnings. Pass `ref={forwardedRef}` added and version bumped to 1.5.6. to see whether this fixes the warnings.

Pass forward refs

---

libs/juno-ui-components/src/components/Checkbox/Checkbox.test.js
libs/juno-ui-components/src/components/CheckboxGroup/CheckboxGroup.component.js
libs/juno-ui-components/src/components/CheckboxGroup/CheckboxGroup.test.js
libs/juno-ui-components/src/components/Form/Form.stories.js
libs/juno-ui-components/src/components/Radio/Radio.test.js
libs/juno-ui-components/src/components/RadioGroup/RadioGroup.test.js
libs/juno-ui-components/src/components/Select/Select.component.js
libs/juno-ui-components/src/components/Select/Select.test.js
libs/juno-ui-components/src/components/Switch/Switch.component.js
libs/juno-ui-components/src/components/Switch/Switch.test.js
libs/juno-ui-components/src/components/TextInput/TextInput.component.js
libs/juno-ui-components/src/components/TextInput/TextInput.test.js
libs/juno-ui-components/src/components/Textarea/Textarea.component.js
libs/juno-ui-components/src/components/Textarea/Textarea.test.js

This PR introduces unique ids being generated for all input elements and their associated labels if no id was passed. 
* Checkbox
* CheckboxGroup
* Radio
* RadioGroup
* Select
* Switch
* Textarea
* TextInput

Forms unique ids

---

libs/juno-ui-components/src/components/CheckboxRow/CheckboxRow.component.js
libs/juno-ui-components/src/components/CheckboxRow/CheckboxRow.stories.js
libs/juno-ui-components/src/components/RadioRow/RadioRow.component.js
libs/juno-ui-components/src/components/RadioRow/RadioRow.stories.js
libs/juno-ui-components/src/components/SelectRow/SelectRow.component.js
libs/juno-ui-components/src/components/SelectRow/SelectRow.stories.js
libs/juno-ui-components/src/components/SwitchRow/SwitchRow.component.js
libs/juno-ui-components/src/components/SwitchRow/SwitchRow.stories.js
libs/juno-ui-components/src/components/TextInputRow/TextInputRow.component.js
libs/juno-ui-components/src/components/TextInputRow/TextInputRow.stories.js
libs/juno-ui-components/src/components/TextareaRow/TextareaRow.component.js
libs/juno-ui-components/src/components/TextareaRow/TextareaRow.stories.js

RadioRow, CheckboxRow, SelectRow, SwitchRow, TextareaRow, and TextInputRow now only return a FormRow wrapping the respective input element. All props are being passed to the input element now.

[ui] [input type]-Row components return FormRow and input element

---

libs/juno-ui-components/src/components/Select/Select.component.js
libs/juno-ui-components/src/components/Select/select.scss

* prevent Select trigger button label (representing the selected value) from being cutt off when rendering a label

[ui] don’t cut off Select value when rendering a label

---

libs/juno-ui-components/src/components/Select/Select.component.js
libs/juno-ui-components/src/components/Select/Select.test.js

* add `onChange` handler to Select for consistency with the rest of Juno. Both `onChange` and `onValueChange` will run when the select changes.

[ui] Select: allow `onValueChange` and `onChange` handlers

---

libs/juno-ui-components/package.json
libs/juno-ui-components/src/components/AppShell/AppShell.component.js
libs/juno-ui-components/src/components/AppShell/AppShell.test.js
libs/juno-ui-components/src/components/MainContainerInner/MainContainerInner.component.js
libs/juno-ui-components/src/components/MainContainerInner/MainContainerInner.test.js

* In embedded mode, we render full-width content by default
* In non-embedded/default mode, we render width-restricted content
* in both modes, users can pass `fullWidthContent` explictlty for desired non-default behaviour

[ui] AppShell: properly handle full-width/responsive behaviour

---

libs/juno-ui-components/package.json
libs/juno-ui-components/src/components/ComboBox/ComboBox.component.js
libs/juno-ui-components/src/components/ComboBox/ComboBox.test.js
libs/juno-ui-components/src/components/ComboBoxOption/ComboBoxOption.component.js

* Store value  and value label pairs in a map in `ComboBox` state
* Provide a callback via context to individual `ComboBoxOption` elements to pass their info to the `ComboBox` parent

Combobox values labels context

---

libs/juno-ui-components/src/docs/ColorPalette/ColorPalette.jsx
libs/juno-ui-components/src/docs/ColorPalette/JunoColorPalette.jsx
libs/juno-ui-components/src/docs/ColorPalette/TailwindColors.js
libs/juno-ui-components/src/docs/ColorPalette/generateTailwindThemeClassesJson.js
libs/juno-ui-components/src/docs/JunoComponentParent/JunoComponentParent.jsx
libs/juno-ui-components/src/docs/JunoComponentWrapper/JunoComponentWrapper.jsx
libs/juno-ui-components/src/docs/colors.mdx
libs/juno-ui-components/src/docsHidden/examplePage.mdx

Added a the component JunoComponentParent for mdx files.  The component allows the usage of tailwind classes for the child components while also handling theme changes.
fixes #472 
added juno-red to allowlist #466 
Implemented JunoComponentParent in the example page and color-page and reducing boilerplate code in the other ColorPalette.
TBD: Renaming the component to ComponentParent  or ComponentWrapper

[Storybook] component wrapper

---

libs/juno-ui-components/package.json
libs/juno-ui-components/src/components/Modal/Modal.component.js
libs/juno-ui-components/src/components/Modal/Modal.stories.js
libs/juno-ui-components/src/components/Modal/Modal.test.js

* render `aria-labelledby` only if the modal has a heading that can be referenced, i.e. `title` or `heading` have been passed.
* add `ariaLabel` prop so there is an explicit way to add an accessible name to a modal even if it does not have a heading or title
* fix some story args to remove console errors

Modal improvements

---

apps/supernova/package.json
apps/supernova/src/lib/createFiltersSlice.js
apps/supernova/src/lib/createFiltersSlice.test.js
package-lock.json

Supernova don't crash when there are labels which are not a string. Instead it ignores these labels. This behaviour is also tested.

[supernova] Tests for the filter compontent and corrected expected behaviour.

---

libs/juno-ui-components/package.json
libs/juno-ui-components/src/components/SideNavigation/SideNavigation.test.js
libs/juno-ui-components/src/components/SideNavigationItem/SideNavigationItem.component.js
libs/juno-ui-components/src/components/SideNavigationItem/SideNavigationItem.test.js
libs/juno-ui-components/src/components/TabNavigation/TabNavigation.test.js
libs/juno-ui-components/src/components/TabNavigationItem/TabNavigationItem.component.js
libs/juno-ui-components/src/components/TabNavigationItem/TabNavigationItem.test.js
package-lock.json

[juno-ui-components]: fixed reseting active attribute in SideNavigationItem and TabNavigationItem. Added tests with rerender function.

---

libs/juno-ui-components/package.json
libs/juno-ui-components/src/components/DateTimePicker/DateTimePicker.component.js
libs/juno-ui-components/src/components/DateTimePicker/DateTimePicker.stories.js
libs/juno-ui-components/src/components/DateTimePicker/DateTimePicker.test.js

Closes #563. 
**Issue 1 – browser warning re non-conforming value in minute input when `enableTime` is set to true** 
Set the default `minuteIncrement` to 1, thus preventing the first issue descried.
**Issue 2 – onChange handler not firing every time when value (time) changes**
Add heuristic to determine a working default `dateFormat` depending on `enableTime`, `enableSeconds`, and `noCalendar`. As a result, users should never have to set a `dateFormat` themselves in order to have a working component. They are still free to set a custom date format that suits their needs.
**Issue 3 – defaultHour and defaultMinute** 
Rename the story not raise wrong expectations, update/clarify the respective prop and story descriptions.

[ui] DateTimePicker: add correct dateFormat to story

---

libs/juno-ui-components/package.json
libs/juno-ui-components/src/components/AppShellProvider/AppShellProvider.test.js

Tests were not running and had to be skipped since the div was rendered into a shadowRoot node that need specific attention when testing. Setting shadowRoot to `false` for testing unrelated functionality.

Unskip AppShellProvider tests

---

apps/greenhouse/package.json
apps/greenhouse/src/hooks/useApi.js
package-lock.json

This PR fixes the api endpoint to get `Plugins` from (formerly `PluginConfigs`)
**Please do only merge in sync with greenhouse core, this is a breaking change!**
Out of scope:
- Renaming / Refactoring variable and parameter naming. This ONLY fixes the api endpoint.
cc @IvoGoman

feat(gh): rename crds

---

libs/juno-ui-components/package.json
libs/juno-ui-components/src/components/DateTimePicker/DateTimePicker.component.js
libs/juno-ui-components/src/components/DateTimePicker/DateTimePicker.stories.js
libs/juno-ui-components/src/components/DateTimePicker/DateTimePicker.test.js
libs/juno-ui-components/src/components/DateTimePicker/datetimepicker.scss

Fix #575
Fix #578 
Listening to our `value` prop (and its aliases) in a `useEffect` to set the flatpickr instance, and enforcing `onChange` events to update our state on the onChange resulting in our updating the FP instance caused an endless loop. We now JSON.stringify the `value` prop and its aliases and keep these in our dependency array, so they will only be recognized as changed when they _actually have changed_, eventually preventing DateTimePicker from going into an endless loop.
The problem was caused by some weird behavior of the `open()` method of the flatpickr instance that we used in `handleCalendarIconClick`. In order to avoid having to use this method, we remove the calendar icon button element completely, and set the calendar icon (or clock icon for pure time pickers) as an …

DateTimerPicker fix endless loop. Fixes #575, #578

---

ci/Dockerfile.assets.server

I tested this by stripping down the Dockerfile and just running the nginx inside which now no longer complains about this problem and if you fix the subfilter and would provide a tls cert, it would probably start.

Fix nginx config

---

ci/helm-charts/assets_server_ha/templates/service.yaml

to advertise the /32 IP to upstream

[helm-chart] set service externalTrafficPolicy to Local

---

ci/pipeline.yaml.erb

Ensure npm build is executed on all packages before the main build process.
In the pipeline, we handle two different repositories (due to historical reasons). If the packages come from **@cloudoperators/juno**, which is a monorepo, we must first run the build on all dependent packages. This is done using `npm run build`. Only after this step can we proceed with the build task for the current package, ensuring that all dependencies are properly compiled and up-to-date.

chore(build): run npm build on all packages before building a package

---

ci/helm-charts/hosting/templates/deployment.yaml
ci/helm-charts/hosting/templates/index-html-configmap.yaml
ci/helm-charts/hosting/templates/nginx-configmap.yaml

This PR updates the Helm charts to load the dashboard app from Elektra instead of the assets-server. As part of decommissioning the assets-server, the dashboard's source code has been migrated to Elektra.
- The dashboard needs to be hosted on different DNSs.
- Elektra supports standalone widgets, which allows us to load the dashboard directly from Elektra.

chore(dashboard): changes the helm charts

---

ci/helm-charts/hosting/templates/index-html-configmap.yaml

This PR adds a timestamp to the url of landing page widget. This allows us to load every time the latest state of the widget.

chore(ci): adds a timestamp to src url

---

ci/pipeline.yaml.erb
e2e/cypress/integration/hosting/dashboard.spec.js
e2e/run.sh

this PR will fix the dashboard hosting tests for the global dashboard and remove all old apps and libs from the CI

chore(ci): fix tests and cleanup

---

ci/helm-charts/assets_server/templates/deployment.yaml
ci/helm-charts/assets_server_ha/templates/deployment.yaml

This PR sets the replica count for the assets-server to 0. This change is necessary to perform a scream test before permanently terminating the service.

chore(assets-server): set replicas to 0 for assets-server
