libs/juno-ui-components/src/components/IntroBox/IntroBox.component.js, libs/juno-ui-components/src/components/IntroBox/IntroBox.stories.js, libs/juno-ui-components/src/components/IntroBox/IntroBox.test.js, libs/juno-ui-components/src/components/IntroBox/index.js
No tailwind styling yet, only classed (without any visible effect) for now.
=> Add Introbox component 

libs/juno-ui-components/src/components/Switch/Switch.component.js, libs/juno-ui-components/src/components/Switch/Switch.stories.js, libs/juno-ui-components/src/components/Switch/Switch.test.js, libs/juno-ui-components/src/components/Switch/index.js
Adds a fully functional Switch / Toggle component. Styles are still missing, assigning classes depending on state is working though.
=> Add a Switch component

libs/juno-ui-components/src/components/CheckboxGroup/CheckboxGroup.component.js, libs/juno-ui-components/src/components/CheckboxGroup/CheckboxGroup.stories.js, libs/juno-ui-components/src/components/CheckboxGroup/CheckboxGroup.test.js, libs/juno-ui-components/src/components/CheckboxGroup/index.js, libs/juno-ui-components/src/components/Select/Select.component.js, libs/juno-ui-components/src/components/Select/Select.test.js, libs/juno-ui-components/src/components/SelectGroup/SelectGroup.component.js, libs/juno-ui-components/src/components/SelectGroup/SelectGroup.test.js, libs/juno-ui-components/src/components/Switch/Switch.component.js, libs/juno-ui-components/src/components/Switch/Switch.test.js, libs/juno-ui-components/src/components/SwitchGroup/SwitchGroup.component.js, libs/juno-ui-components/src/components/SwitchGroup/SwitchGroup.stories.js, libs/juno-ui-components/src/components/SwitchGroup/SwitchGroup.test.js, libs/juno-ui-components/src/components/SwitchGroup/index.js, libs/juno-ui-components/src/components/TextInputGroup/TextInputGroup.component.js, libs/juno-ui-components/src/components/TextInputGroup/TextInputGroup.test.js, libs/juno-ui-components/src/components/Textarea/Textarea.component.js, libs/juno-ui-components/src/components/Textarea/Textarea.test.js, libs/juno-ui-components/src/components/TextareaGroup/TextareaGroup.component.js, libs/juno-ui-components/src/components/TextareaGroup/TextareaGroup.stories.js, libs/juno-ui-components/src/components/TextareaGroup/TextareaGroup.test.js, libs/juno-ui-components/src/components/TextareaGroup/index.js
* add SelectGroup component
* add CheckboxGroup component
* add TextareaGroup component
* add SwitchGroup component
* add onChange to Select
* add onChange to TextInputGroup
* add onChange to Textarea
* add Test for onChange handler to TextInputGroup
TODO: 
* fix onChange handler/test for CheckboxGroup
* fix checked state and onChange  handlers tests for Switch
* fix SwitchGroup stories / prop passing and state for Switch
=> Form improvements

libs/juno-ui-components/src/components/Tooltip/Tooltip.component.js, libs/juno-ui-components/src/components/Tooltip/Tooltip.stories.js, libs/juno-ui-components/src/components/Tooltip/Tooltip.test.js, libs/juno-ui-components/src/components/Tooltip/index.js
Just a start, needs improvements to be useful.
=> add a rudimentary tooltip component

libs/juno-ui-components/src/components/FormSection/FormSection.component.js, libs/juno-ui-components/src/components/IntroBox/IntroBox.component.js, libs/juno-ui-components/src/components/Message/Message.component.js, libs/juno-ui-components/src/components/RadioRow/RadioRow.component.js, libs/juno-ui-components/src/components/SelectRow/SelectRow.component.js, libs/juno-ui-components/src/components/SwitchRow/SwitchRow.component.js, libs/juno-ui-components/src/components/TextInputRow/TextInputRow.component.js, libs/juno-ui-components/src/components/TextareaRow/TextareaRow.component.js
adds descriptive classnames to components to help identify and debug when inspecting source.
=> add descriptive classnames

libs/juno-ui-components/src/components/Button/Button.component.js, libs/juno-ui-components/src/components/CheckboxRow/CheckboxRow.component.js, libs/juno-ui-components/src/components/Message/Message.component.js, libs/juno-ui-components/src/components/Message/Message.stories.js, libs/juno-ui-components/src/components/RadioRow/RadioRow.component.js, libs/juno-ui-components/src/components/SelectRow/SelectRow.component.js, libs/juno-ui-components/src/components/SwitchRow/SwitchRow.component.js, libs/juno-ui-components/src/components/SwitchRow/SwitchRow.stories.js, libs/juno-ui-components/src/components/TextInput/TextInput.component.js, libs/juno-ui-components/src/components/TextInputRow/TextInputRow.component.js, libs/juno-ui-components/src/components/TextInputRow/TextInputRow.stories.js, libs/juno-ui-components/src/components/Textarea/Textarea.component.js, libs/juno-ui-components/src/components/TextareaRow/TextareaRow.component.js, libs/juno-ui-components/src/components/Tooltip/Tooltip.component.js, libs/juno-ui-components/src/global.scss, libs/juno-ui-components/tailwind.config.js
Begin applying new visual design, mainly to form elements. Good to merge but not complete.
=> Design update

libs/juno-ui-components/src/components/CheckboxRow/CheckboxRow.component.js, libs/juno-ui-components/src/components/CheckboxRow/CheckboxRow.test.js, libs/juno-ui-components/src/components/Label/Label.component.js, libs/juno-ui-components/src/components/Label/Label.stories.js, libs/juno-ui-components/src/components/Label/Label.test.js, libs/juno-ui-components/src/components/Label/index.js, libs/juno-ui-components/src/components/RadioRow/RadioRow.component.js, libs/juno-ui-components/src/components/SelectRow/SelectRow.component.js, libs/juno-ui-components/src/components/SwitchRow/SwitchRow.component.js, libs/juno-ui-components/src/components/TextInputRow/TextInputRow.component.js, libs/juno-ui-components/src/components/TextareaRow/TextareaRow.component.js
Add a re-usable Label component and use it in all relevant form-row components.
=> Re usable label

libs/juno-ui-components/src/components/Button/Button.component.js, libs/juno-ui-components/src/components/Button/Button.stories.js, libs/juno-ui-components/src/global.scss, libs/juno-ui-components/tailwind.config.js
TODO: border-color not working
=> Add subdued button

libs/juno-ui-components/src/components/ClickableIcon/ClickableIcon.component.js, libs/juno-ui-components/src/components/ClickableIcon/ClickableIcon.stories.js, libs/juno-ui-components/src/components/ClickableIcon/ClickableIcon.test.js, libs/juno-ui-components/src/components/ClickableIcon/index.js, libs/juno-ui-components/src/components/Tooltip/Tooltip.component.js
also use ClickableIcon in Tooltip component
=> Add ClickableIcon component

libs/juno-ui-components/src/components/Checkbox/Checkbox.component.js, libs/juno-ui-components/src/components/Checkbox/Checkbox.stories.js, libs/juno-ui-components/src/components/Checkbox/Checkbox.test.js, libs/juno-ui-components/src/components/CheckboxRow/CheckboxRow.component.js, libs/juno-ui-components/src/components/CheckboxRow/CheckboxRow.test.js, libs/juno-ui-components/src/global.scss, libs/juno-ui-components/tailwind.config.js
adds a controlled Checkbox component, use it in CheckboxRow component
=> Controlled checkbox

libs/juno-ui-components/src/components/Button/Button.component.js, libs/juno-ui-components/src/components/Button/Button.test.js, libs/juno-ui-components/src/components/Checkbox/Checkbox.test.js, libs/juno-ui-components/src/components/CheckboxRow/CheckboxRow.test.js, libs/juno-ui-components/src/components/Form/Form.component.js, libs/juno-ui-components/src/components/Form/Form.test.js, libs/juno-ui-components/src/components/FormSection/FormSection.component.js, libs/juno-ui-components/src/components/FormSection/FormSection.test.js, libs/juno-ui-components/src/components/Icon/Icon.test.js, libs/juno-ui-components/src/components/Radio/Radio.test.js, libs/juno-ui-components/src/components/RadioRow/RadioRow.component.js, libs/juno-ui-components/src/components/RadioRow/RadioRow.test.js, libs/juno-ui-components/src/components/Select/Select.component.js, libs/juno-ui-components/src/components/Select/Select.test.js, libs/juno-ui-components/src/components/Switch/Switch.component.js, libs/juno-ui-components/src/components/Switch/Switch.test.js, libs/juno-ui-components/src/components/SwitchRow/SwitchRow.component.js, libs/juno-ui-components/src/components/SwitchRow/SwitchRow.test.js, libs/juno-ui-components/src/components/TextInput/TextInput.component.js, libs/juno-ui-components/src/components/TextInput/TextInput.stories.js, libs/juno-ui-components/src/components/TextInput/TextInput.test.js, libs/juno-ui-components/src/components/Textarea/Textarea.component.js, libs/juno-ui-components/src/components/Textarea/Textarea.test.js
Covers tests and implementation changes for:
* Button
* Checkbox
* Form
* FormSection
* Icon
* IntroBox
* Radio
* RadioGroup
* RadioRow
* Select
* Switch
* SwitchRow
* TextInput
=> Test coverage general No1

libs/juno-ui-components/src/components/Select/Select.component.js, libs/juno-ui-components/src/components/SelectRow/SelectRow.component.js, libs/juno-ui-components/src/components/TextInputRow/TextInputRow.component.js, libs/juno-ui-components/src/components/TextareaRow/TextareaRow.component.js
* set TextInput, TextArea, Select to 100% width in their parent container in the respective […]Row component
* add right padding to Select so text and icon don't collide
=> Input width

libs/juno-ui-components/src/components/Form/Form.component.js, libs/juno-ui-components/src/components/FormSection/FormSection.component.js
* add styles for Form and FormSection headings
=> Form headings

libs/juno-ui-components/src/components/ButtonRow/ButtonRow.component.js, libs/juno-ui-components/src/components/ButtonRow/ButtonRow.stories.js, libs/juno-ui-components/src/components/ButtonRow/ButtonRow.test.js, libs/juno-ui-components/src/components/ButtonRow/index.js, libs/juno-ui-components/src/index.js
=> Button row

libs/juno-ui-components/src/components/Button/Button.component.js, libs/juno-ui-components/src/components/Checkbox/Checkbox.test.js, libs/juno-ui-components/src/components/ClickableIcon/ClickableIcon.test.js, libs/juno-ui-components/src/components/Radio/Radio.test.js, libs/juno-ui-components/src/components/Select/Select.test.js, libs/juno-ui-components/src/components/Switch/Switch.test.js, libs/juno-ui-components/src/components/TextInput/TextInput.test.js, libs/juno-ui-components/src/components/Textarea/Textarea.test.js
* adds test for not executing a. handler on disabled elements
* remove disabled logic form Button to use native behaviour
=> [ui] add tests for disabled

libs/juno-ui-components/src/components/IntroBox/IntroBox.component.js, libs/juno-ui-components/src/global.scss, libs/juno-ui-components/tailwind.config.js
adds new Introbox styles:
* lighter background
* colored left border
=> Introbox update

libs/juno-ui-components/README.md
=> Read me updates

libs/juno-ui-components/src/components/DataGridToolbar/DataGridToolbar.component.js
* resolve circular dependency build error
=> [ui] Remove unused Import

libs/juno-ui-components/src/components/DataGridBody/DataGridBody.stories.js, libs/juno-ui-components/src/components/DataGridCell/DataGridCell.stories.js, libs/juno-ui-components/src/components/DataGridCheckboxCell/DataGridCheckboxCell.stories.js, libs/juno-ui-components/src/components/DataGridFoot/DataGridFoot.stories.js, libs/juno-ui-components/src/components/DataGridFootRow/DataGridFootRow.stories.js, libs/juno-ui-components/src/components/DataGridHead/DataGridHead.stories.js, libs/juno-ui-components/src/components/DataGridHeadCell/DataGridHeadCell.stories.js, libs/juno-ui-components/src/components/DataGridHeadRow/DataGridHeadRow.stories.js, libs/juno-ui-components/src/components/DataGridRow/DataGridRow.stories.js
* use storybook decorators to define valid parent dom structure for stories to render in
=> [ui] render stories in valid parent nodes

libs/juno-ui-components/.storybook/main.js, libs/juno-ui-components/rollup.config.js, libs/juno-ui-components/src/components/Icon/Icon.component.js, libs/juno-ui-components/src/components/Icon/Icon.test.js
* add customizable title prop to Icon component
=> Icon titles

libs/juno-ui-components/src/components/Icon/Icon.component.js, libs/juno-ui-components/src/components/PageHeader/PageHeader.component.js, libs/juno-ui-components/src/components/SearchInput/SearchInput.component.js, libs/juno-ui-components/src/components/SelectOption/SelectOption.component.js, libs/juno-ui-components/src/components/SelectOptionGroup/SelectOptionGroup.component.js, libs/juno-ui-components/src/components/Spinner/Spinner.component.js
* Make sure all components use empty string (`""`) as defaultProp for className
=> Prevent classname null

libs/juno-ui-components/src/components/DataGrid/DataGrid.stories.js, libs/juno-ui-components/src/components/DataGridBody/DataGridBody.stories.js, libs/juno-ui-components/src/components/DataGridCell/DataGridCell.stories.js, libs/juno-ui-components/src/components/DataGridCheckboxCell/DataGridCheckboxCell.stories.js, libs/juno-ui-components/src/components/DataGridFoot/DataGridFoot.stories.js, libs/juno-ui-components/src/components/DataGridFootRow/DataGridFootRow.stories.js, libs/juno-ui-components/src/components/DataGridHead/DataGridHead.stories.js, libs/juno-ui-components/src/components/DataGridHeadCell/DataGridHeadCell.stories.js, libs/juno-ui-components/src/components/DataGridHeadRow/DataGridHeadRow.stories.js, libs/juno-ui-components/src/components/DataGridRow/DataGridRow.component.js, libs/juno-ui-components/src/components/DataGridRow/DataGridRow.stories.js
* prevent output of `boundTemplate` in storybook code examples
=> Improve datagrid

libs/juno-ui-components/src/components/Button/Button.component.js, libs/juno-ui-components/src/components/Button/Button.stories.js, libs/juno-ui-components/src/components/Button/Button.test.js, libs/juno-ui-components/src/components/Spinner/Spinner.component.js, libs/juno-ui-components/src/components/Spinner/Spinner.stories.js, libs/juno-ui-components/src/components/Spinner/Spinner.test.js
* add a `progress` prop to show a spinner in a button while an action triggered by the button is in progress
* In case the button has an icon, the spinner will replace the icon while in progress
* add a `color` prop to `Spinner` component to accept a color class the same way `Icon` does
=> Progress Button

libs/juno-ui-components/src/components/Icon/Icon.component.js, libs/juno-ui-components/src/components/Icon/Icon.test.js
* add aria-label from title-prop when rendering an anchor or button
* use icon-prop as fallback for aria-label
=> [ui] Icon: add aria-label to anchor and button

libs/juno-ui-components/src/components/Button/Button.component.js, libs/juno-ui-components/src/components/Button/Button.test.js
* Update paddings and icon margins of small and default button sizes according to latest spec
=> [ui] Button: update paddings, icon margin

libs/juno-ui-components/src/components/Badge/Badge.stories.js
Allow users to select icon for badge via a select in storybook.
=> [ui] Badge: Story: add custom control for icon

libs/juno-ui-components/src/components/Button/Button.component.js, libs/juno-ui-components/src/components/Button/Button.stories.js, libs/juno-ui-components/src/components/Icon/Icon.component.js
* add select controls for icon, variant
=> Button icon stories

libs/juno-ui-components/src/components/Select/Select.component.js, libs/juno-ui-components/src/components/SelectRow/SelectRow.component.js, libs/juno-ui-components/src/components/SelectRow/SelectRow.test.js, libs/juno-ui-components/src/components/TextInputRow/TextInputRow.component.js, libs/juno-ui-components/src/components/TextInputRow/TextInputRow.test.js, libs/juno-ui-components/src/components/TextareaRow/TextareaRow.component.js, libs/juno-ui-components/src/components/TextareaRow/TextareaRow.test.js
* adds 'floating' variant to Select and uses it as a default
* adds tests for floating vs stacked layout variants to SelectRow, TextInputRow, TextareaRow
=> Select floating label

libs/juno-ui-components/src/components/CodeBlock/CodeBlock.component.js, libs/juno-ui-components/src/global.scss, libs/juno-ui-components/tailwind.config.js
* add top border to bottom bar / footer
* adjust/reduce padding in bottom bar / footer
=> Codeblock update

libs/juno-ui-components/src/components/Container/Container.component.js, libs/juno-ui-components/src/components/Container/Container.stories.js, libs/juno-ui-components/src/components/Container/Container.test.js
* adds prop to add vertical padding, default is `false`
=> [ui] Container: add `py`-prop

libs/juno-ui-components/package.json, libs/juno-ui-components/src/components/Modal/Modal.component.js, libs/juno-ui-components/src/components/Modal/Modal.stories.js
* adds in-depth description text in storybook
* adds a story with custom ModalFooter 
* version 0.7.6
=> Modal docs

libs/juno-ui-components/package.json, libs/juno-ui-components/src/components/SideNavigation/SideNavigation.component.js, libs/juno-ui-components/src/components/SideNavigation/SideNavigation.stories.js, libs/juno-ui-components/src/components/SideNavigation/SideNavigation.test.js, libs/juno-ui-components/src/components/SideNavigation/index.js, libs/juno-ui-components/src/components/SideNavigationItem/SideNavigationItem.component.js, libs/juno-ui-components/src/components/SideNavigationItem/SideNavigationItem.stories.js, libs/juno-ui-components/src/components/SideNavigationItem/SideNavigationItem.test.js, libs/juno-ui-components/src/components/SideNavigationItem/index.js, libs/juno-ui-components/src/components/SideNavigationItem/sideNavigationItem.scss
Adds `SideNavigation` and `SideNavigationItem` components.
=> SideNavigation

libs/juno-ui-components/package.json, libs/juno-ui-components/src/components/Modal/Modal.component.js, libs/juno-ui-components/src/components/ModalFooter/ModalFooter.component.js, libs/juno-ui-components/src/global.scss, libs/juno-ui-components/tailwind.config.js
update Modal backdrop colors/opacities
=> Modal backdrop update

libs/juno-ui-components/package.json, libs/juno-ui-components/src/components/Button/Button.component.js, libs/juno-ui-components/src/components/Button/Button.stories.js
* Add stories for buttons with Icon only as prop and as child
* simplify h-margins css
=> Icon only button

libs/juno-ui-components/package.json, libs/juno-ui-components/src/components/Badge/Badge.component.js, libs/juno-ui-components/src/components/BreadcrumbItem/BreadcrumbItem.component.js, libs/juno-ui-components/src/components/Icon/Icon.component.js, libs/juno-ui-components/src/components/SearchInput/SearchInput.component.js, libs/juno-ui-components/src/components/Select/Select.component.js, libs/juno-ui-components/src/components/TextInputRow/TextInputRow.component.js
* Removes `inline-block` from Icon svg element
* handles side effects in other components
* add some icon positioning improvements / fixes
* bumps version to 1.5.1
=> Icon remove inline block

libs/juno-ui-components/package.json, libs/juno-ui-components/src/components/Button/Button.component.js, libs/juno-ui-components/src/components/Button/button.scss
* fixes the Button height for small and default sizes across all variants, compensating for the border of `subdued`, too.
=> Fix button height

libs/juno-ui-components/package.json, libs/juno-ui-components/src/components/Button/Button.component.js
=> bump version to 1.5.5

apps/exampleapp/src/components/EditItemPanel.js, apps/exampleapp/src/components/LogInModal.js, apps/exampleapp/src/components/NewItemModal.js
Updates the forms in example app to use palin input elements wrapped in generic `FormRow`.
=> Exampleapp update to Forms 2.0

libs/juno-ui-components/src/components/Select/Select.component.js
* use state variable `isOpen` to open Select Menu (was using prop `open` before)
=> Fix select open vs isOpen

apps/assets-overview/src/components/AssetDetails.js, apps/assets-overview/src/components/AssetsListItem.js, apps/assets-overview/src/components/Documentation.js, apps/assets-overview/src/components/details/PreviewAppPropsForm.jsx, apps/greenhouse/src/components/nav/PluginNav.js, apps/volta/src/components/CertificateList.js, apps/volta/src/components/NewCertificateForm.js, apps/whois/src/ResultItem.js
fixes #426 #428 #434 and used FormRow instead of stack in Volta
=> [Juno][asset-overview][volta] updated colors and components to standards

libs/juno-ui-components/package.json, libs/juno-ui-components/src/components/ComboBox/ComboBox.component.js, libs/juno-ui-components/src/components/ComboBox/ComboBox.stories.js, libs/juno-ui-components/src/components/Modal/Modal.stories.js
* Fixes clipping on overflow: hidden parent elements
* Render ComboBox menu into a portal provided by PortalProvider
* Add story with ComboBox in Modal
=> [ui] ComboBox: don’t clip menu

apps/greenhouse/src/components/Plugin.jsx, package-lock.json
=> [greenhouse] hardcoded embedded apps

apps/volta/package.json, apps/volta/src/App.js
=> [Volta] Fix rewriteRoutes for cases that the endpoint not necessarily -

apps/greenhouse-management/package.json, apps/greenhouse/package.json
* set sub dependencies to latest
=> feat(gh) release 0.1.10

apps/greenhouse-management/package.json, apps/greenhouse/package.json
Releases:
gh 0.1.13 with
- gh-mgnt 1.0.8 with
- cluster-admin 1.6.1
- team-admin 1.0
=> feat(greenhouse): release 0.1.13

apps/greenhouse/src/components/Auth.jsx, apps/supernova/package.json, package-lock.json
fixes #514 
Fade-in for greenhouse is now deleted.
=> [greenhouse] delete transition

apps/greenhouse/package.json, apps/greenhouse/src/components/Plugin.jsx, apps/greenhouse/src/components/PluginContainer.jsx, package-lock.json
Tabs now unmount even if unmounting is trigged before mounting is done, new mounting
fixes #521
=> [greenhouse] consistent loading messages, new mounting and unmounting of plugins

apps/greenhouse-management/package.json, package-lock.json
=> Add plugin admin

libs/juno-ui-components/package.json, libs/juno-ui-components/src/components/PortalProvider/PortalProvider.component.js, libs/juno-ui-components/src/components/PortalProvider/PortalProvider.test.js
* remove obsolete skipped tests
* add tests
=> Test portalprovider

apps/greenhouse-management/package.json, package-lock.json
Increment Version of plugin-admin to the newest.
=> [greenhouse-mgmt] new version for plugin-admin

apps/greenhouse-management/package.json, package-lock.json
=> [greenhouse-mgmt] update cluster admin

ci/helm-charts/hosting/templates/index-html-configmap.yaml
set the value for the dashboard region dynamically
=> fix(dashboard): set region

package-lock.json, packages/volta/package.json, packages/whois/package.json
=> chore(core): update dependencies

packages/volta/jest.config.js, packages/volta/package-lock.json, packages/volta/src/App.test.js, packages/whois/jest.config.js
This PR fixes the tests in packages whois and volta.
=> fix(test): fixes the tests in packages
